### ISSUE TITLE
Customize fonts

### ISSUE THREAD

**Issue by leafac** [stathissideris/ditaa#13]
Currently Ditaa builds diagrams using the [system `Dialog` font](https://github.com/stathissideris/ditaa/blob/39eaa429a6922eb6af9087122a0d82c0fd5eb658/src/org/stathissideris/ascii2image/graphics/FontMeasurer.java#L40), as mapped by the JVM, with [point size 12](https://github.com/stathissideris/ditaa/blob/39eaa429a6922eb6af9087122a0d82c0fd5eb658/src/org/stathissideris/ascii2image/graphics/FontMeasurer.java#L143).

Is anyone interested in command line parameters that allows the user to choose a font and its point size? I propose a roadmap and I'm volunteering to implement the feature myself, if more people are interested and the maintainer is willing to consider the feature.
# Roadmap
- [ ] Choose command line parameter. _I propose `-f, --font` and `-F, --font-size`_.
- [ ] Decide which action to take when font isn't found on the system. Either fall back to the default `Dialog` and emit a warning or completely halt the program. _I propose terminating right away_.
- [ ] Parse command line parameters.
- [ ] Modify `FontMeasurer` to parameterize over font and point size.
- [ ] Add error handling.
- [ ] Add documentation about feature.

**Comment by skang404** [comment]
I request this please

**Comment by leafac** [comment]
Apparently, [this has been done](https://github.com/pepijnve/ditaa/commit/714808f762da780724eabe9172326db708873366).

Now it's to the upstream to consider whether this is worth having.

**Comment by leafac** [comment]
Closing this as stale.
